apiVersion: v1
kind: Service
metadata:
  name: resume-parser-service
spec:
  type: NodePort # Exposes it outside Minikube
  selector:
    app: resume-parser
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000