apiVersion: v1
kind: Service
metadata:
  name: mlflow-service # This name is important!
spec:
  selector:
    app: mlflow-server
  ports:
    - protocol: TCP
      port: 5000       # Port other pods will use to talk to it
      targetPort: 5000 # Port on the MLflow pod
  # type: ClusterIP # (Default) Only accessible inside K8s
  # We'll use port-forwarding to access it locally later.